# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

K2_Ep_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_rcpp`, u)
}

K2_Ep_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_diff1_rcpp`, u)
}

K2_Ep_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_diff2_rcpp`, u)
}

K2_Bw_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Bw_rcpp`, u)
}

K2_Bw_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Bw_diff1_rcpp`, u)
}

K2_Bw_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Bw_diff2_rcpp`, u)
}

K4_Bw_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K4_Bw_rcpp`, u)
}

K4_Bw_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K4_Bw_diff1_rcpp`, u)
}

K4_Bw_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K4_Bw_diff2_rcpp`, u)
}

K2_G_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_G_rcpp`, u)
}

K2_G_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_G_diff1_rcpp`, u)
}

K2_G_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_G_diff2_rcpp`, u)
}

KDE_rcpp <- function(X, x, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_KDE_rcpp`, X, x, h, kernel, w)
}

KNW_rcpp <- function(Y, X, x, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_KNW_rcpp`, Y, X, x, h, kernel, w)
}

KNWcdf_rcpp <- function(Y, y, X, x, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_KNWcdf_rcpp`, Y, y, X, x, h, kernel, w)
}

CVKNW_rcpp <- function(Y, X, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_CVKNW_rcpp`, Y, X, h, kernel, w)
}

CVKNWcdf_rcpp <- function(Y, X, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_CVKNWcdf_rcpp`, Y, X, h, kernel, w)
}

LSKNW_rcpp <- function(Y, X, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_LSKNW_rcpp`, Y, X, h, kernel, w)
}

LSKNWcdf_rcpp <- function(Y, X, h, kernel = "K2_Ep", w = NULL) {
    .Call(`_MYHfusionRcpp_LSKNWcdf_rcpp`, Y, X, h, kernel, w)
}

lL_normal_rcpp <- function(X, Y, alpha, beta, sigma, w = NULL) {
    .Call(`_MYHfusionRcpp_lL_normal_rcpp`, X, Y, alpha, beta, sigma, w)
}

diff_lL_normal_rcpp <- function(X, Y, alpha, beta, sigma, w = NULL) {
    .Call(`_MYHfusionRcpp_diff_lL_normal_rcpp`, X, Y, alpha, beta, sigma, w)
}

lL_logistic_rcpp <- function(X, Y, alpha, beta, w = NULL) {
    .Call(`_MYHfusionRcpp_lL_logistic_rcpp`, X, Y, alpha, beta, w)
}

diff_lL_logistic_rcpp <- function(X, Y, alpha, beta, w = NULL) {
    .Call(`_MYHfusionRcpp_diff_lL_logistic_rcpp`, X, Y, alpha, beta, w)
}

lL_Gamma_rcpp <- function(X, Y, alpha, beta, nu, w = NULL) {
    .Call(`_MYHfusionRcpp_lL_Gamma_rcpp`, X, Y, alpha, beta, nu, w)
}

diff_lL_Gamma_rcpp <- function(X, Y, alpha, beta, nu, w = NULL) {
    .Call(`_MYHfusionRcpp_diff_lL_Gamma_rcpp`, X, Y, alpha, beta, nu, w)
}

lL_binomial_rcpp <- function(X, Y, alpha, beta, N, w = NULL) {
    .Call(`_MYHfusionRcpp_lL_binomial_rcpp`, X, Y, alpha, beta, N, w)
}

diff_lL_binomial_rcpp <- function(X, Y, alpha, beta, N, w = NULL) {
    .Call(`_MYHfusionRcpp_diff_lL_binomial_rcpp`, X, Y, alpha, beta, N, w)
}

lL_Poisson_rcpp <- function(X, Y, alpha, beta, w = NULL) {
    .Call(`_MYHfusionRcpp_lL_Poisson_rcpp`, X, Y, alpha, beta, w)
}

diff_lL_Poisson_rcpp <- function(X, Y, alpha, beta, w = NULL) {
    .Call(`_MYHfusionRcpp_diff_lL_Poisson_rcpp`, X, Y, alpha, beta, w)
}

lL_Poisson_rcpp_v1 <- function(X, Y, alpha, beta) {
    .Call(`_MYHfusionRcpp_lL_Poisson_rcpp_v1`, X, Y, alpha, beta)
}

lL_Poisson_w_rcpp_v1 <- function(X, Y, alpha, beta, w) {
    .Call(`_MYHfusionRcpp_lL_Poisson_w_rcpp_v1`, X, Y, alpha, beta, w)
}

diff_lL_Poisson_rcpp_v1 <- function(X, Y, alpha, beta) {
    .Call(`_MYHfusionRcpp_diff_lL_Poisson_rcpp_v1`, X, Y, alpha, beta)
}

cumuSIR_rcpp <- function(X, Y, eps_inv) {
    .Call(`_MYHfusionRcpp_cumuSIR_rcpp`, X, Y, eps_inv)
}

SolveLagrange_AD_EY_normal_rcpp <- function(X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_AD_EY_normal_rcpp`, X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_AD_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_AD_EY_normal_rcpp`, X, alpha, beta, sigma, phi, eta, diff_size)
}

SolveLagrange_AD_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_AD_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_AD_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, y_pts, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_AD_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, y_pts, eta, diff_size)
}

SolveLagrange_AD_EYsubX_normal_rcpp <- function(X, alpha, beta, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_AD_EYsubX_normal_rcpp`, X, alpha, beta, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_AD_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, inclusion, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_AD_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, inclusion, eta, diff_size)
}

mean_psi_ADCS_EY_normal_rcpp <- function(X, alpha, beta, phi, CS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADCS_EY_normal_rcpp`, X, alpha, beta, phi, CS_beta)
}

SolveLagrange_ADCS_EY_normal_rcpp <- function(X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADCS_EY_normal_rcpp`, X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADCS_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADCS_EY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, eta, diff_size)
}

mean_psi_ADCS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts) {
    .Call(`_MYHfusionRcpp_mean_psi_ADCS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts)
}

SolveLagrange_ADCS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADCS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADCS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADCS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts, eta, diff_size)
}

mean_psi_ADCS_EYsubX_normal_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion) {
    .Call(`_MYHfusionRcpp_mean_psi_ADCS_EYsubX_normal_rcpp`, X, alpha, beta, phi, CS_beta, inclusion)
}

SolveLagrange_ADCS_EYsubX_normal_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADCS_EYsubX_normal_rcpp`, X, alpha, beta, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADCS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, inclusion, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADCS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, inclusion, eta, diff_size)
}

mean_psi_ADPPS_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta)
}

SolveLagrange_ADPPS_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta, diff_size)
}

mean_psi_ADPPS_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta)
}

SolveLagrange_ADPPS_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta, diff_size)
}

mean_psi_ADPPS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts)
}

SolveLagrange_ADPPS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta, diff_size)
}

mean_psi_ADPPS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion)
}

SolveLagrange_ADPPS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta, diff_size)
}

SolveLagrange_AD_EY_logistic_rcpp <- function(X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_AD_EY_logistic_rcpp`, X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_AD_EY_logistic_rcpp <- function(X, alpha, beta, phi, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_AD_EY_logistic_rcpp`, X, alpha, beta, phi, eta, diff_size)
}

SolveLagrange_AD_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_AD_EXsubY_logistic_rcpp`, X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_AD_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_AD_EXsubY_logistic_rcpp`, X, alpha, beta, phi, eta, diff_size)
}

SolveLagrange_AD_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_AD_EYsubX_logistic_rcpp`, X, alpha, beta, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_AD_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, inclusion, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_AD_EYsubX_logistic_rcpp`, X, alpha, beta, phi, inclusion, eta, diff_size)
}

mean_psi_ADCS_EY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADCS_EY_logistic_rcpp`, X, alpha, beta, phi, CS_beta)
}

SolveLagrange_ADCS_EY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADCS_EY_logistic_rcpp`, X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADCS_EY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADCS_EY_logistic_rcpp`, X, alpha, beta, phi, CS_beta, eta, diff_size)
}

mean_psi_ADCS_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADCS_EXsubY_logistic_rcpp`, X, alpha, beta, phi, CS_beta)
}

SolveLagrange_ADCS_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADCS_EXsubY_logistic_rcpp`, X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADCS_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADCS_EXsubY_logistic_rcpp`, X, alpha, beta, phi, CS_beta, eta, diff_size)
}

mean_psi_ADCS_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion) {
    .Call(`_MYHfusionRcpp_mean_psi_ADCS_EYsubX_logistic_rcpp`, X, alpha, beta, phi, CS_beta, inclusion)
}

SolveLagrange_ADCS_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADCS_EYsubX_logistic_rcpp`, X, alpha, beta, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADCS_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADCS_EYsubX_logistic_rcpp`, X, alpha, beta, phi, CS_beta, inclusion, eta, diff_size)
}

mean_psi_ADPPS_EX_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EX_logistic_rcpp`, X, alpha, beta, phi, PPS_beta)
}

SolveLagrange_ADPPS_EX_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EX_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EX_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EX_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, eta, diff_size)
}

mean_psi_ADPPS_EY_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EY_logistic_rcpp`, X, alpha, beta, phi, PPS_beta)
}

SolveLagrange_ADPPS_EY_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EY_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EY_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EY_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, eta, diff_size)
}

mean_psi_ADPPS_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, inclusion) {
    .Call(`_MYHfusionRcpp_mean_psi_ADPPS_EYsubX_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, inclusion)
}

SolveLagrange_ADPPS_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_SolveLagrange_ADPPS_EYsubX_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

grad_psi_ADPPS_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, PPS_beta, inclusion, eta, diff_size) {
    .Call(`_MYHfusionRcpp_grad_psi_ADPPS_EYsubX_logistic_rcpp`, X, alpha, beta, phi, PPS_beta, inclusion, eta, diff_size)
}

AD_EY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, eta) {
    .Call(`_MYHfusionRcpp_AD_EY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, eta)
}

AD_EY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EXsubY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, y_pts, eta) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, y_pts, eta)
}

AD_EXsubY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol)
}

AD_EXsubY_Gamma_rcpp <- function(X, alpha, beta, nu, phi, y_pts) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_Gamma_rcpp`, X, alpha, beta, nu, phi, y_pts)
}

AD_EYsubX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, inclusion, eta) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, inclusion, eta)
}

AD_EYsubX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta)
}

ADPPS_EX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta)
}

ADPPS_EY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EXsubY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, y_pts, eta)
}

ADPPS_EXsubY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EYsubX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, inclusion, eta)
}

ADPPS_EYsubX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

ADCS_EY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, eta)
}

ADCS_EY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADCS_EXsubY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, y_pts, eta)
}

ADCS_EXsubY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol)
}

ADCS_EYsubX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, inclusion, eta)
}

ADCS_EYsubX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

pinv_rcpp <- function(M_A) {
    .Call(`_MYHfusionRcpp_pinv_rcpp`, M_A)
}

solve_rcpp <- function(M_A, M_B) {
    .Call(`_MYHfusionRcpp_solve_rcpp`, M_A, M_B)
}

inv_sympd_rcpp <- function(M_S) {
    .Call(`_MYHfusionRcpp_inv_sympd_rcpp`, M_S)
}

eigen_rcpp <- function(M_S) {
    .Call(`_MYHfusionRcpp_eigen_rcpp`, M_S)
}

chol_rcpp <- function(M_S) {
    .Call(`_MYHfusionRcpp_chol_rcpp`, M_S)
}

rcond_rcpp <- function(A) {
    .Call(`_MYHfusionRcpp_rcond_rcpp`, A)
}

GroupSum_rcpp <- function(MM, id) {
    .Call(`_MYHfusionRcpp_GroupSum_rcpp`, MM, id)
}

eXsq_rcpp <- function(data_X) {
    .Call(`_MYHfusionRcpp_eXsq_rcpp`, data_X)
}

eXsq_w_rcpp <- function(data_X, weight) {
    .Call(`_MYHfusionRcpp_eXsq_w_rcpp`, data_X, weight)
}

Xsq_lowtri_rcpp <- function(data_X) {
    .Call(`_MYHfusionRcpp_Xsq_lowtri_rcpp`, data_X)
}

twoXYsym_lowtri_rcpp <- function(data_X, data_Y) {
    .Call(`_MYHfusionRcpp_twoXYsym_lowtri_rcpp`, data_X, data_Y)
}

ctingP_rcpp <- function(Y, y) {
    .Call(`_MYHfusionRcpp_ctingP_rcpp`, Y, y)
}

ctingP_uni_rcpp <- function(Y, y) {
    .Call(`_MYHfusionRcpp_ctingP_uni_rcpp`, Y, y)
}

countAinB_rcpp <- function(A, B) {
    .Call(`_MYHfusionRcpp_countAinB_rcpp`, A, B)
}

countAinB_W_rcpp <- function(A, B, W_B) {
    .Call(`_MYHfusionRcpp_countAinB_W_rcpp`, A, B, W_B)
}

rankAinB_rcpp <- function(A, B) {
    .Call(`_MYHfusionRcpp_rankAinB_rcpp`, A, B)
}

rankAinB_W_rcpp <- function(A, B, W_B) {
    .Call(`_MYHfusionRcpp_rankAinB_W_rcpp`, A, B, W_B)
}

outer_times_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_times_rcpp`, a, b)
}

outer_minus_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_minus_rcpp`, a, b)
}

outer_plus_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_plus_rcpp`, a, b)
}

outer_leq_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_leq_rcpp`, a, b)
}

outer_geq_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_geq_rcpp`, a, b)
}

rcpparma_hello_world <- function() {
    .Call(`_MYHfusionRcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MYHfusionRcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MYHfusionRcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MYHfusionRcpp_rcpparma_bothproducts`, x)
}

testfunction_rcpp <- function(a, my_r_func) {
    .Call(`_MYHfusionRcpp_testfunction_rcpp`, a, my_r_func)
}

KME_exact_rcpp <- function(time_last, is_event, time_event) {
    .Call(`_MYHfusionRcpp_KME_exact_rcpp`, time_last, is_event, time_event)
}

KME_at_times_rcpp <- function(time_event, time_points, S_event = NULL, H_event = NULL) {
    .Call(`_MYHfusionRcpp_KME_at_times_rcpp`, time_event, time_points, S_event, H_event)
}

SKME_exact_rcpp <- function(time_last, is_event, time_event, X, x, h, kernel = "K2_Ep") {
    .Call(`_MYHfusionRcpp_SKME_exact_rcpp`, time_last, is_event, time_event, X, x, h, kernel)
}

