# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

K2_Ep_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_rcpp`, u)
}

K2_Ep_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_diff1_rcpp`, u)
}

K2_Ep_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_diff2_rcpp`, u)
}

K2_Bw_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Bw_rcpp`, u)
}

K2_Bw_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Bw_diff1_rcpp`, u)
}

K2_Bw_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Bw_diff2_rcpp`, u)
}

K4_Bw_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K4_Bw_rcpp`, u)
}

K4_Bw_diff1_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K4_Bw_diff1_rcpp`, u)
}

K4_Bw_diff2_rcpp <- function(u) {
    .Call(`_MYHfusionRcpp_K4_Bw_diff2_rcpp`, u)
}

KDE_K2Ep_rcpp <- function(X, x, h) {
    .Call(`_MYHfusionRcpp_KDE_K2Ep_rcpp`, X, x, h)
}

KDE_K2Ep_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHfusionRcpp_KDE_K2Ep_w_rcpp`, X, x, h, w)
}

KDE_K2Bw_rcpp <- function(X, x, h) {
    .Call(`_MYHfusionRcpp_KDE_K2Bw_rcpp`, X, x, h)
}

KDE_K2Bw_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHfusionRcpp_KDE_K2Bw_w_rcpp`, X, x, h, w)
}

KDE_K4Bw_rcpp <- function(X, x, h) {
    .Call(`_MYHfusionRcpp_KDE_K4Bw_rcpp`, X, x, h)
}

KDE_K4Bw_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHfusionRcpp_KDE_K4Bw_w_rcpp`, X, x, h, w)
}

KNW_K2Ep_rcpp <- function(Y, X, x, h) {
    .Call(`_MYHfusionRcpp_KNW_K2Ep_rcpp`, Y, X, x, h)
}

KNW_K2Ep_w_rcpp <- function(Y, X, x, h, w) {
    .Call(`_MYHfusionRcpp_KNW_K2Ep_w_rcpp`, Y, X, x, h, w)
}

KNW_K2Bw_rcpp <- function(Y, X, x, h) {
    .Call(`_MYHfusionRcpp_KNW_K2Bw_rcpp`, Y, X, x, h)
}

KNW_K2Bw_w_rcpp <- function(Y, X, x, h, w) {
    .Call(`_MYHfusionRcpp_KNW_K2Bw_w_rcpp`, Y, X, x, h, w)
}

KNW_K4Bw_rcpp <- function(Y, X, x, h) {
    .Call(`_MYHfusionRcpp_KNW_K4Bw_rcpp`, Y, X, x, h)
}

KNW_K4Bw_w_rcpp <- function(Y, X, x, h, w) {
    .Call(`_MYHfusionRcpp_KNW_K4Bw_w_rcpp`, Y, X, x, h, w)
}

CVKNW_K2Ep_rcpp <- function(Y, X, h) {
    .Call(`_MYHfusionRcpp_CVKNW_K2Ep_rcpp`, Y, X, h)
}

CVKNW_K2Bw_rcpp <- function(Y, X, h) {
    .Call(`_MYHfusionRcpp_CVKNW_K2Bw_rcpp`, Y, X, h)
}

CVKNW_K4Bw_rcpp <- function(Y, X, h) {
    .Call(`_MYHfusionRcpp_CVKNW_K4Bw_rcpp`, Y, X, h)
}

CVKNWcdf_K2Ep_rcpp <- function(Y, X, h) {
    .Call(`_MYHfusionRcpp_CVKNWcdf_K2Ep_rcpp`, Y, X, h)
}

K2_Ep_rcpp_v1 <- function(u) {
    .Call(`_MYHfusionRcpp_K2_Ep_rcpp_v1`, u)
}

lL_normal_rcpp <- function(X, Y, alpha, beta, sigma) {
    .Call(`_MYHfusionRcpp_lL_normal_rcpp`, X, Y, alpha, beta, sigma)
}

lL_normal_w_rcpp <- function(X, Y, alpha, beta, sigma, w) {
    .Call(`_MYHfusionRcpp_lL_normal_w_rcpp`, X, Y, alpha, beta, sigma, w)
}

diff_lL_normal_rcpp <- function(X, Y, alpha, beta, sigma) {
    .Call(`_MYHfusionRcpp_diff_lL_normal_rcpp`, X, Y, alpha, beta, sigma)
}

lL_logistic_rcpp <- function(X, Y, alpha, beta) {
    .Call(`_MYHfusionRcpp_lL_logistic_rcpp`, X, Y, alpha, beta)
}

lL_logistic_w_rcpp <- function(X, Y, alpha, beta, w) {
    .Call(`_MYHfusionRcpp_lL_logistic_w_rcpp`, X, Y, alpha, beta, w)
}

diff_lL_logistic_rcpp <- function(X, Y, alpha, beta) {
    .Call(`_MYHfusionRcpp_diff_lL_logistic_rcpp`, X, Y, alpha, beta)
}

lL_Gamma_rcpp <- function(X, Y, alpha, beta, nu) {
    .Call(`_MYHfusionRcpp_lL_Gamma_rcpp`, X, Y, alpha, beta, nu)
}

lL_Gamma_w_rcpp <- function(X, Y, alpha, beta, nu, w) {
    .Call(`_MYHfusionRcpp_lL_Gamma_w_rcpp`, X, Y, alpha, beta, nu, w)
}

diff_lL_Gamma_rcpp <- function(X, Y, alpha, beta, nu) {
    .Call(`_MYHfusionRcpp_diff_lL_Gamma_rcpp`, X, Y, alpha, beta, nu)
}

lL_binomial_rcpp <- function(X, Y, alpha, beta, N) {
    .Call(`_MYHfusionRcpp_lL_binomial_rcpp`, X, Y, alpha, beta, N)
}

lL_binomial_w_rcpp <- function(X, Y, alpha, beta, N, w) {
    .Call(`_MYHfusionRcpp_lL_binomial_w_rcpp`, X, Y, alpha, beta, N, w)
}

diff_lL_binomial_rcpp <- function(X, Y, alpha, beta, N) {
    .Call(`_MYHfusionRcpp_diff_lL_binomial_rcpp`, X, Y, alpha, beta, N)
}

lL_Poisson_rcpp <- function(X, Y, alpha, beta) {
    .Call(`_MYHfusionRcpp_lL_Poisson_rcpp`, X, Y, alpha, beta)
}

lL_Poisson_w_rcpp <- function(X, Y, alpha, beta, w) {
    .Call(`_MYHfusionRcpp_lL_Poisson_w_rcpp`, X, Y, alpha, beta, w)
}

diff_lL_Poisson_rcpp <- function(X, Y, alpha, beta) {
    .Call(`_MYHfusionRcpp_diff_lL_Poisson_rcpp`, X, Y, alpha, beta)
}

lL_normal_rcpp_fun <- function(X, Y, alpha, beta, sigma) {
    .Call(`_MYHfusionRcpp_lL_normal_rcpp_fun`, X, Y, alpha, beta, sigma)
}

lL_normal_w_rcpp_fun <- function(X, Y, alpha, beta, sigma, w) {
    .Call(`_MYHfusionRcpp_lL_normal_w_rcpp_fun`, X, Y, alpha, beta, sigma, w)
}

diff_lL_normal_rcpp_v1 <- function(X, Y, alpha, beta, sigma) {
    .Call(`_MYHfusionRcpp_diff_lL_normal_rcpp_v1`, X, Y, alpha, beta, sigma)
}

AD_EY_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, eta) {
    .Call(`_MYHfusionRcpp_AD_EY_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, eta)
}

AD_EY_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EY_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi) {
    .Call(`_MYHfusionRcpp_AD_EY_normal_rcpp`, X, alpha, beta, sigma, phi)
}

ADvar_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, eta) {
    .Call(`_MYHfusionRcpp_ADvar_EY_normal_rcpp`, X, alpha, beta, sigma, phi, eta)
}

AD_EXsubY_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, y_pts, eta) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, y_pts, eta)
}

AD_EXsubY_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, y_pts) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, y_pts)
}

ADvar_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADvar_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, y_pts, eta)
}

AD_EYsubX_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, inclusion, eta) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, inclusion, eta)
}

AD_EYsubX_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, inclusion) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, inclusion)
}

ADvar_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADvar_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, inclusion, eta)
}

ADCS_EY_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EY_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, CS_beta, eta)
}

ADCS_EY_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADCS_EY_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADCS_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta) {
    .Call(`_MYHfusionRcpp_ADCS_EY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta)
}

ADCSvar_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCSvar_EY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, eta)
}

ADCS_EXsubY_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts, eta)
}

ADCS_EXsubY_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADCS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts)
}

ADCSvar_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADCSvar_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, y_pts, eta)
}

ADCS_EYsubX_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, CS_beta, inclusion, eta)
}

ADCS_EYsubX_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADCS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, inclusion) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, inclusion)
}

ADCSvar_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, CS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADCSvar_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, CS_beta, inclusion, eta)
}

ADPPS_EX_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta)
}

ADPPS_EX_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADPPS_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta)
}

ADPPSvar_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPSvar_EX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta)
}

ADPPS_EY_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta)
}

ADPPS_EY_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADPPS_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta)
}

ADPPSvar_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPSvar_EY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, eta)
}

ADPPS_EXsubY_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta)
}

ADPPS_EXsubY_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADPPS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts)
}

ADPPSvar_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADPPSvar_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, y_pts, eta)
}

ADPPS_EYsubX_normal_Lagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_normal_Lagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta)
}

ADPPS_EYsubX_normal_SolveLagrange_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_normal_SolveLagrange_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADPPS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion)
}

ADPPSvar_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADPPSvar_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, PPS_beta, inclusion, eta)
}

AD_EY_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, eta) {
    .Call(`_MYHfusionRcpp_AD_EY_logistic_Lagrange_rcpp`, X, alpha, beta, phi, eta)
}

AD_EY_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EY_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EY_logistic_rcpp <- function(X, alpha, beta, phi) {
    .Call(`_MYHfusionRcpp_AD_EY_logistic_rcpp`, X, alpha, beta, phi)
}

ADvar_EY_logistic_rcpp <- function(X, alpha, beta, phi, eta) {
    .Call(`_MYHfusionRcpp_ADvar_EY_logistic_rcpp`, X, alpha, beta, phi, eta)
}

AD_EXsubY_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, eta) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_logistic_Lagrange_rcpp`, X, alpha, beta, phi, eta)
}

AD_EXsubY_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_logistic_rcpp`, X, alpha, beta, phi)
}

ADvar_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, eta) {
    .Call(`_MYHfusionRcpp_ADvar_EXsubY_logistic_rcpp`, X, alpha, beta, phi, eta)
}

AD_EYsubX_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, inclusion, eta) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_logistic_Lagrange_rcpp`, X, alpha, beta, phi, inclusion, eta)
}

AD_EYsubX_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

AD_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, inclusion) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_logistic_rcpp`, X, alpha, beta, phi, inclusion)
}

ADvar_EYsubX_logistic_rcpp <- function(X, alpha, beta, phi, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADvar_EYsubX_logistic_rcpp`, X, alpha, beta, phi, inclusion, eta)
}

ADCS_EY_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EY_logistic_Lagrange_rcpp`, X, alpha, beta, phi, CS_beta, eta)
}

ADCS_EY_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADCS_EY_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADCS_EY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta) {
    .Call(`_MYHfusionRcpp_ADCS_EY_logistic_rcpp`, X, alpha, beta, phi, CS_beta)
}

ADCSvar_EY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCSvar_EY_logistic_rcpp`, X, alpha, beta, phi, CS_beta, eta)
}

ADCS_EXsubY_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_logistic_Lagrange_rcpp`, X, alpha, beta, phi, CS_beta, eta)
}

ADCS_EXsubY_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol, eps_inv)
}

ADCS_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_logistic_rcpp`, X, alpha, beta, phi, CS_beta)
}

ADCSvar_EXsubY_logistic_rcpp <- function(X, alpha, beta, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCSvar_EXsubY_logistic_rcpp`, X, alpha, beta, phi, CS_beta, eta)
}

ADCS_EYsubX_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_logistic_Lagrange_rcpp`, X, alpha, beta, phi, CS_beta, inclusion, eta)
}

ADCS_EYsubX_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EX_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_logistic_Lagrange_rcpp`, X, alpha, beta, phi, PPS_beta, eta)
}

ADPPS_EX_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EY_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_logistic_Lagrange_rcpp`, X, alpha, beta, phi, PPS_beta, eta)
}

ADPPS_EY_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EYsubX_logistic_Lagrange_rcpp <- function(X, alpha, beta, phi, PPS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_logistic_Lagrange_rcpp`, X, alpha, beta, phi, PPS_beta, inclusion, eta)
}

ADPPS_EYsubX_logistic_SolveLagrange_rcpp <- function(X, alpha, beta, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_logistic_SolveLagrange_rcpp`, X, alpha, beta, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

AD_EY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, eta) {
    .Call(`_MYHfusionRcpp_AD_EY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, eta)
}

AD_EY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_AD_EY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, eta_initial, iter_max, step_rate, step_max, tol)
}

AD_EY_Gamma_rcpp <- function(X, alpha, beta, nu, phi) {
    .Call(`_MYHfusionRcpp_AD_EY_Gamma_rcpp`, X, alpha, beta, nu, phi)
}

AD_EXsubY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, y_pts, eta) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, y_pts, eta)
}

AD_EXsubY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, y_pts, eta_initial, iter_max, step_rate, step_max, tol)
}

AD_EXsubY_Gamma_rcpp <- function(X, alpha, beta, nu, phi, y_pts) {
    .Call(`_MYHfusionRcpp_AD_EXsubY_Gamma_rcpp`, X, alpha, beta, nu, phi, y_pts)
}

AD_EYsubX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, inclusion, eta) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, inclusion, eta)
}

AD_EYsubX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_AD_EYsubX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta)
}

ADPPS_EX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta)
}

ADPPS_EY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EXsubY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, y_pts, eta)
}

ADPPS_EXsubY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EXsubY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol)
}

ADPPS_EYsubX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, inclusion, eta)
}

ADPPS_EYsubX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADPPS_EYsubX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, PPS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

ADCS_EY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, eta)
}

ADCS_EY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, eta_initial, iter_max, step_rate, step_max, tol)
}

ADCS_EXsubY_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, y_pts, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, y_pts, eta)
}

ADCS_EXsubY_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EXsubY_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, y_pts, eta_initial, iter_max, step_rate, step_max, tol)
}

ADCS_EYsubX_Gamma_Lagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, inclusion, eta) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_Gamma_Lagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, inclusion, eta)
}

ADCS_EYsubX_Gamma_SolveLagrange_rcpp <- function(X, alpha, beta, nu, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol) {
    .Call(`_MYHfusionRcpp_ADCS_EYsubX_Gamma_SolveLagrange_rcpp`, X, alpha, beta, nu, phi, CS_beta, inclusion, eta_initial, iter_max, step_rate, step_max, tol)
}

pinv_rcpp <- function(M_A) {
    .Call(`_MYHfusionRcpp_pinv_rcpp`, M_A)
}

solve_rcpp <- function(M_A, M_B) {
    .Call(`_MYHfusionRcpp_solve_rcpp`, M_A, M_B)
}

inv_sympd_rcpp <- function(M_S) {
    .Call(`_MYHfusionRcpp_inv_sympd_rcpp`, M_S)
}

eigen_rcpp <- function(M_S) {
    .Call(`_MYHfusionRcpp_eigen_rcpp`, M_S)
}

chol_rcpp <- function(M_S) {
    .Call(`_MYHfusionRcpp_chol_rcpp`, M_S)
}

rcond_rcpp <- function(A) {
    .Call(`_MYHfusionRcpp_rcond_rcpp`, A)
}

GroupSum_rcpp <- function(MM, id) {
    .Call(`_MYHfusionRcpp_GroupSum_rcpp`, MM, id)
}

eXsq_rcpp <- function(data_X) {
    .Call(`_MYHfusionRcpp_eXsq_rcpp`, data_X)
}

eXsq_w_rcpp <- function(data_X, weight) {
    .Call(`_MYHfusionRcpp_eXsq_w_rcpp`, data_X, weight)
}

Xsq_lowtri_rcpp <- function(data_X) {
    .Call(`_MYHfusionRcpp_Xsq_lowtri_rcpp`, data_X)
}

twoXYsym_lowtri_rcpp <- function(data_X, data_Y) {
    .Call(`_MYHfusionRcpp_twoXYsym_lowtri_rcpp`, data_X, data_Y)
}

ctingP_rcpp <- function(Y, y) {
    .Call(`_MYHfusionRcpp_ctingP_rcpp`, Y, y)
}

ctingP_uni_rcpp <- function(Y, y) {
    .Call(`_MYHfusionRcpp_ctingP_uni_rcpp`, Y, y)
}

countAinB_rcpp <- function(A, B) {
    .Call(`_MYHfusionRcpp_countAinB_rcpp`, A, B)
}

countAinB_W_rcpp <- function(A, B, W_B) {
    .Call(`_MYHfusionRcpp_countAinB_W_rcpp`, A, B, W_B)
}

rankAinB_rcpp <- function(A, B) {
    .Call(`_MYHfusionRcpp_rankAinB_rcpp`, A, B)
}

rankAinB_W_rcpp <- function(A, B, W_B) {
    .Call(`_MYHfusionRcpp_rankAinB_W_rcpp`, A, B, W_B)
}

outer_times_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_times_rcpp`, a, b)
}

outer_minus_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_minus_rcpp`, a, b)
}

outer_plus_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_plus_rcpp`, a, b)
}

outer_leq_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_leq_rcpp`, a, b)
}

outer_geq_rcpp <- function(a, b) {
    .Call(`_MYHfusionRcpp_outer_geq_rcpp`, a, b)
}

pinv_rcpp_v1 <- function(M_A) {
    .Call(`_MYHfusionRcpp_pinv_rcpp_v1`, M_A)
}

pinv_rcpp_v2 <- function(M_A) {
    .Call(`_MYHfusionRcpp_pinv_rcpp_v2`, M_A)
}

pinv_rcpp_v3 <- function(M_A) {
    .Call(`_MYHfusionRcpp_pinv_rcpp_v3`, M_A)
}

pinv_rcpp_v4 <- function(M_A) {
    .Call(`_MYHfusionRcpp_pinv_rcpp_v4`, M_A)
}

eigen_rcpp_v1 <- function(M_S) {
    .Call(`_MYHfusionRcpp_eigen_rcpp_v1`, M_S)
}

rcpparma_hello_world <- function() {
    .Call(`_MYHfusionRcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_MYHfusionRcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_MYHfusionRcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_MYHfusionRcpp_rcpparma_bothproducts`, x)
}

testfunction_rcpp <- function(a, my_r_func) {
    .Call(`_MYHfusionRcpp_testfunction_rcpp`, a, my_r_func)
}

KME_rcpp <- function(time_last, is_event, time_event) {
    .Call(`_MYHfusionRcpp_KME_rcpp`, time_last, is_event, time_event)
}

